/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;

/**
 *
 * @author Acer
 */
public class EstadoPedido extends javax.swing.JFrame {

    /**
     * Creates new form EstadoPedido
     */
    public EstadoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        MetodoPago = new javax.swing.JLabel();
        Domiciliario = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Tiempo = new javax.swing.JLabel();
        Restaurante = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 100, 30));

        jButton2.setText("Volver");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 100, 30));

        MetodoPago.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        getContentPane().add(MetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 200, 50));

        Domiciliario.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        getContentPane().add(Domiciliario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 200, 70));

        Estado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, 30));

        Tiempo.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        getContentPane().add(Tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 190, 20));

        Restaurante.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        getContentPane().add(Restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 130, 30));

        Cantidad.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        Cantidad.setForeground(new java.awt.Color(51, 0, 204));
        getContentPane().add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 70, 30));

        Producto.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(51, 0, 204));
        getContentPane().add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, 30));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 110, 20));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/output-onlinepngtools (1).png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoPedido().setVisible(true);
            }
        });
    }

    public EstadoPedido(String pUsuario) {
       initComponents();
        String usuarioa = pUsuario;
        user.setText(usuarioa);
        this.setLocationRelativeTo(null);
        
        
            
    }
    
    private void mostrarInformacionPedido()
    {
        consultasBaseDeDatos consulta = new BaseDeDatos();
      
                 
   
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JLabel Domiciliario;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel MetodoPago;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Restaurante;
    private javax.swing.JLabel Tiempo;
    private javax.swing.JLabel fondo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
