/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class EstadoPedido extends javax.swing.JFrame {

    /**
     * Creates new form EstadoPedido
     */
    public EstadoPedido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        direccion = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        MetodoPago = new javax.swing.JLabel();
        Domiciliario = new javax.swing.JLabel();
        Estado = new javax.swing.JLabel();
        Restaurante = new javax.swing.JLabel();
        Producto = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resumen.setColumns(20);
        resumen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        resumen.setRows(5);
        jScrollPane1.setViewportView(resumen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 550, 150));

        direccion.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 510, 60));

        ID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 110, 40));

        MetodoPago.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(MetodoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 600, 340, 60));

        Domiciliario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(Domiciliario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 500, 40));

        Estado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(Estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 390, 40));

        Restaurante.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Restaurante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 180, 40));

        Producto.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        Producto.setForeground(new java.awt.Color(51, 0, 204));
        Producto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(Producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 170, 150));

        user.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 310, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/d (1).png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        Cancelar.setForeground(new java.awt.Color(255, 0, 0));
        Cancelar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 120, 40));

        Atras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        getContentPane().add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        // TODO add your handling code here:
        PantallaVerPedidos vp = new PantallaVerPedidos(user.getText(),Restaurante.getText());
            vp.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_AtrasActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // TODO add your handling code here:
        consultasBaseDeDatos consulta = new BaseDeDatos();
        int i=Integer.parseInt(ID.getText()); 
        if(consulta.ModificarEstadoPedido("cancelado", i))
        {
            JOptionPane.showMessageDialog(null, "Se ha cancelado tu pedido.");
            consulta.flagearCliente(user.getText(), Restaurante.getText());
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Han pasado más de cinco minutos, el pedido ya no es cancelable.");
        }
        PantallaInicialCliente vp = new PantallaInicialCliente(user.getText());
            vp.setVisible(true);
            this.dispose();
            
    }//GEN-LAST:event_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EstadoPedido().setVisible(true);
            }
        });
    }

    
    
    public EstadoPedido(int idpedido, String usuario, String restaurante) {
       initComponents();
       transparenciaDelBoton();
        int id = idpedido;
        user.setText(usuario);
        ID.setText(String.valueOf(id));
         Restaurante.setText(restaurante);
        this.setLocationRelativeTo(null);
        mostrarInformacionPedido();

            
    }
    public void transparenciaDelBoton(){
       Atras.setOpaque(false);
       Atras.setBackground(new Color(0,0,0,0));
       Cancelar.setOpaque(false);
       Cancelar.setBackground(new Color(0,0,0,0));
       
       
       
  }
    
    private void mostrarInformacionPedido()
    {
        consultasBaseDeDatos consulta = new BaseDeDatos();
        int id=Integer.parseInt(ID.getText());  
       //ID.setText(String.valueOf(consulta.darSerialPedido(user.getText())));
       Estado.setText(consulta.DarEstado(id));
       if(consulta.DarDomiciliario(id).equals("0")){
       Domiciliario.setText("Esperando a que alguien tome el pedido.");
       } else {
       Domiciliario.setText(consulta.DarNombreDomiciliario(consulta.DarDomiciliario(id)));
       }       
       ArrayList<String> datosCliente = consulta.darCliente(user.getText());
       direccion.setText(datosCliente.get(2));
       Restaurante.setText(consulta.DarRestPedido(id));
       ArrayList<String> datosCarrito = consulta.darCarroCompras(user.getText());

                     
        for(int i=0;i<datosCarrito.size();i++){
        String[] nr = datosCarrito.get(i).split(",");
        resumen.append( consulta.darDescripcionPlato(nr[0], nr[1]));
        resumen.append(" x " + String.valueOf(consulta.darCantidad(user.getText(), nr[0], nr[1])) + "\n" );
        }

        MetodoPago.setText(String.valueOf(consulta.DarTotalPedido(id)));
       
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Cancelar;
    private javax.swing.JLabel Domiciliario;
    private javax.swing.JLabel Estado;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel MetodoPago;
    private javax.swing.JLabel Producto;
    private javax.swing.JLabel Restaurante;
    private javax.swing.JLabel direccion;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resumen;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
