/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author samyf
 */
public class PantallaModificarAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ModificarAdmin
     */
    String Usuario;
    
    public PantallaModificarAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jTextFieldCampoUsuario.setText(Usuario);
    }
        public PantallaModificarAdmin(String pUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        Usuario=pUsuario;
    }
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jTextFieldCampoUsuario = new javax.swing.JTextField();
        jPasswordFieldCampoContrasena = new javax.swing.JPasswordField();
        jButtonModificarUsuario = new javax.swing.JButton();
        jButtonModificarContrasena = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 140, 40));

        jTextFieldCampoUsuario.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(jTextFieldCampoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 150, 30));

        jPasswordFieldCampoContrasena.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        getContentPane().add(jPasswordFieldCampoContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 150, 30));

        jButtonModificarUsuario.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButtonModificarUsuario.setText("Modificar");
        jButtonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        jButtonModificarContrasena.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButtonModificarContrasena.setText("Modificar");
        jButtonModificarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IPantallaModificarAdmin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PantallaInicialAdministrador iniciador = new PantallaInicialAdministrador(Usuario);
        iniciador.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarUsuarioActionPerformed
        // TODO add your handling code here:
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado= false;
        if(this.Usuario.equals(this.jTextFieldCampoUsuario.getText()))
        {
            JOptionPane.showMessageDialog(null, "El usuario anterior es el mismo al nuevo.");
        }
        else if(!this.jTextFieldCampoUsuario.getText().isEmpty())
        {
            resultado=consulta.ModificarUsuario(Usuario, this.jTextFieldCampoUsuario.getText());
            if(resultado)
            {
                JOptionPane.showMessageDialog(null, "Se modifico el usuario.");
                Usuario=this.jTextFieldCampoUsuario.getText();
                PantallaGestionarAdmin iniciador = new PantallaGestionarAdmin(Usuario);
                iniciador.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el usuario.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo Usuario vacio.");
        }
    }//GEN-LAST:event_jButtonModificarUsuarioActionPerformed

    private void jButtonModificarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarContrasenaActionPerformed
        // TODO add your handling code here:
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado= false;

        if(!this.jPasswordFieldCampoContrasena.getText().isEmpty())
        {
            resultado=consulta.ModificarContrasena(Usuario, this.jPasswordFieldCampoContrasena.getText());
            if(resultado)
            {
                JOptionPane.showMessageDialog(null, "Se modifico la contraseña.");
                PantallaGestionarAdmin iniciador = new PantallaGestionarAdmin(Usuario);
                iniciador.setVisible(true);
                this.dispose();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo modificar la contraseña.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo contraseña vacio.");
        }
        
        
    }//GEN-LAST:event_jButtonModificarContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarContrasena;
    private javax.swing.JButton jButtonModificarUsuario;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPasswordField jPasswordFieldCampoContrasena;
    private javax.swing.JTextField jTextFieldCampoUsuario;
    // End of variables declaration//GEN-END:variables
}
