/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author samyf
 */
public class PantallaInicialDomiciliario extends javax.swing.JFrame {

    /**
     * Creates new form PantallaInicialDomiciliario
     */
    public PantallaInicialDomiciliario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.Transparencia();
    }

    public PantallaInicialDomiciliario(String pUsuario) {
        initComponents();
        String users = pUsuario;
        jLabelDomUser.setText(users);
        this.setLocationRelativeTo(null);
        this.Transparencia();
    }

    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }
    
    public void Transparencia ()
    {
        this.jButtonCerrarSesion.setOpaque(false);
        this.jButtonCerrarSesion.setBackground(new Color(0, 0, 0, 0));
        this.jButtonVerPerfil.setOpaque(false);
        this.jButtonVerPerfil.setBackground(new Color(0, 0, 0, 0));
        this.verdisponibles.setOpaque(false);
        this.verdisponibles.setBackground(new Color(0, 0, 0, 0));
        this.jButtonVerPedidosEnCurso.setOpaque(false);        
        this.jButtonVerPedidosEnCurso.setBackground(new Color(0, 0, 0, 0));      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelDomUser = new javax.swing.JLabel();
        jButtonVerPerfil = new javax.swing.JButton();
        verdisponibles = new javax.swing.JButton();
        jButtonVerPedidosEnCurso = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(800, 690));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrarSesion.setBorder(null);
        jButtonCerrarSesion.setContentAreaFilled(false);
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 120, 90));

        jLabelDomUser.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabelDomUser.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDomUser.setText("DomUser");
        getContentPane().add(jLabelDomUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jButtonVerPerfil.setBorder(null);
        jButtonVerPerfil.setContentAreaFilled(false);
        jButtonVerPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 200, 210));

        verdisponibles.setBorder(null);
        verdisponibles.setContentAreaFilled(false);
        verdisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verdisponiblesActionPerformed(evt);
            }
        });
        getContentPane().add(verdisponibles, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 180, 220, 210));

        jButtonVerPedidosEnCurso.setBorder(null);
        jButtonVerPedidosEnCurso.setContentAreaFilled(false);
        jButtonVerPedidosEnCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPedidosEnCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerPedidosEnCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 200, 170));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaIniciaDomiciliario.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InicioSesion iniciador = new InicioSesion();
        iniciador.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonVerPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPerfilActionPerformed
        // TODO add your handling code here:
        PantallaPerfilDomiciliario p = new PantallaPerfilDomiciliario(jLabelDomUser.getText());
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVerPerfilActionPerformed

    private void verdisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verdisponiblesActionPerformed
        // TODO add your handling code here:
        PantallaDisnopible disponibles = new PantallaDisnopible(jLabelDomUser.getText());
        disponibles.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verdisponiblesActionPerformed

    private void jButtonVerPedidosEnCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPedidosEnCursoActionPerformed
        // TODO add your handling code here:
        PantallaPedidosEnCursoDomiciliario p = new PantallaPedidosEnCursoDomiciliario(jLabelDomUser.getText());
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVerPedidosEnCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicialDomiciliario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonVerPedidosEnCurso;
    private javax.swing.JButton jButtonVerPerfil;
    private javax.swing.JLabel jLabelDomUser;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JButton verdisponibles;
    // End of variables declaration//GEN-END:variables
}
