/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author Estefania
 */
public class PantallaBusquedaPR extends javax.swing.JFrame {
    
     
    
    public PantallaBusquedaPR() {
        initComponents();
        transparenciaDelBoton();
        inicioVentana();
        this.setLocationRelativeTo(null);   
    }
    /*funcion para agregar icono del programa*/
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }
    public void inicioVentana(){
        // PANTALLA 1: BUSCADOR DE PRODUCTOS/RESTAURANTES
        FondoBuscador.setVisible(true);
        BotonBuscar.setVisible(true);
        EscribirConsulta.setVisible(true);
        BotonAtrasP1.setVisible(true);
        
        //Se desabilita pantalla 2
        FondoMostrarOpciones.setVisible(false);
        InfoBusqueda.setVisible(false);
        ListaBusquedaRestaurantes.setVisible(false);
        BotonRealizarOtra.setVisible(false);
        BotonVerRestaurante.setVisible(false);
        BotonAtrasP2.setVisible(false);
        
        //Se desabilita pantalla 3
        FondoAgregarCarrito.setVisible(false);
        BotonAtrasBusqAnt.setVisible(false);
        BotonAgregarPlatoCC.setVisible(false);
        Confirmacion.setVisible(false);
        BotonOk.setVisible(false);   
    }
    
    public void mostrarPantalla2(){
        
        // PANTALLA 1: BUSCADOR DE PRODUCTOS/RESTAURANTES
        FondoBuscador.setVisible(false);
        BotonBuscar.setVisible(false);
        EscribirConsulta.setVisible(false);
        BotonAtrasP1.setVisible(false);
        
        //Se desabilita pantalla 2
        FondoMostrarOpciones.setVisible(true);
        InfoBusqueda.setVisible(true);
        ListaBusquedaRestaurantes.setVisible(true);
        BotonRealizarOtra.setVisible(true);
        BotonVerRestaurante.setVisible(true);
        BotonAtrasP2.setVisible(true);

        
        //Se desabilita pantalla 3
        FondoAgregarCarrito.setVisible(false);
        BotonAtrasBusqAnt.setVisible(false);
        BotonAgregarPlatoCC.setVisible(false);
        Confirmacion.setVisible(false);
        BotonOk.setVisible(false);
        
    }
    
    public void mostrarPantalla3(){
         // PANTALLA 1: se desabilita
        FondoBuscador.setVisible(false);
        BotonBuscar.setVisible(false);
        EscribirConsulta.setVisible(false);
        BotonAtrasP1.setVisible(false);
        
        //PANTALLA 2: se desabilita 
        FondoMostrarOpciones.setVisible(false);
        InfoBusqueda.setVisible(false);
        ListaBusquedaRestaurantes.setVisible(false);
        BotonRealizarOtra.setVisible(false);
        BotonVerRestaurante.setVisible(false);
        BotonAtrasP2.setVisible(false);
        
        //PANTALLA 3: se activa
        FondoAgregarCarrito.setVisible(true);
        BotonAtrasBusqAnt.setVisible(true);
        BotonAgregarPlatoCC.setVisible(true);
        Confirmacion.setVisible(false);
        BotonOk.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonOk = new javax.swing.JButton();
        Confirmacion = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        BotonAgregarPlatoCC = new javax.swing.JButton();
        BotonAtrasP2 = new javax.swing.JButton();
        BotonAtrasP1 = new javax.swing.JButton();
        BotonAtrasBusqAnt = new javax.swing.JButton();
        EscribirConsulta = new javax.swing.JTextField();
        ListaBusquedaRestaurantes = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        BotonVerRestaurante = new javax.swing.JButton();
        InfoBusqueda = new javax.swing.JTextField();
        BotonRealizarOtra = new javax.swing.JButton();
        FondoAgregarCarrito = new javax.swing.JLabel();
        FondoBuscador = new javax.swing.JLabel();
        FondoMostrarOpciones = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonOk.setBackground(new java.awt.Color(255, 255, 255));
        BotonOk.setFont(new java.awt.Font("Yu Gothic", 0, 36)); // NOI18N
        BotonOk.setText("Ok");
        BotonOk.setBorder(null);
        BotonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonOkMouseClicked(evt);
            }
        });
        getContentPane().add(BotonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 460, 140, 40));

        Confirmacion.setBackground(new java.awt.Color(114, 203, 131));
        Confirmacion.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        Confirmacion.setForeground(new java.awt.Color(255, 255, 255));
        Confirmacion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Confirmacion.setText("SE AGREGÓ CORRECTAMENTE");
        Confirmacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        Confirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmacionActionPerformed(evt);
            }
        });
        getContentPane().add(Confirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 600, 150));

        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, 40));

        BotonAgregarPlatoCC.setBorder(null);
        BotonAgregarPlatoCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgregarPlatoCCMouseClicked(evt);
            }
        });
        getContentPane().add(BotonAgregarPlatoCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 260, 40));

        BotonAtrasP2.setBackground(new java.awt.Color(255, 254, 251));
        BotonAtrasP2.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        BotonAtrasP2.setText("<<  Atrás");
        BotonAtrasP2.setBorder(null);
        BotonAtrasP2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasP2MouseClicked(evt);
            }
        });
        getContentPane().add(BotonAtrasP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, 30));

        BotonAtrasP1.setBackground(new java.awt.Color(255, 255, 255));
        BotonAtrasP1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        BotonAtrasP1.setText("<<  Atrás");
        BotonAtrasP1.setBorder(null);
        getContentPane().add(BotonAtrasP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        BotonAtrasBusqAnt.setBackground(new java.awt.Color(246, 243, 243));
        BotonAtrasBusqAnt.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        BotonAtrasBusqAnt.setText("<< Atrás");
        BotonAtrasBusqAnt.setBorder(null);
        BotonAtrasBusqAnt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAtrasBusqAntMouseClicked(evt);
            }
        });
        getContentPane().add(BotonAtrasBusqAnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, -1));

        EscribirConsulta.setBackground(new java.awt.Color(235, 235, 235));
        EscribirConsulta.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        EscribirConsulta.setBorder(null);
        getContentPane().add(EscribirConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 320, 40));

        jList1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        ListaBusquedaRestaurantes.setViewportView(jList1);

        getContentPane().add(ListaBusquedaRestaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 720, 100));

        BotonVerRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVerRestauranteMouseClicked(evt);
            }
        });
        getContentPane().add(BotonVerRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 230, 40));

        InfoBusqueda.setEditable(false);
        InfoBusqueda.setBackground(new java.awt.Color(235, 235, 235));
        InfoBusqueda.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        InfoBusqueda.setText("jTextField1");
        InfoBusqueda.setBorder(null);
        InfoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(InfoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 360, 40));

        BotonRealizarOtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRealizarOtraMouseClicked(evt);
            }
        });
        getContentPane().add(BotonRealizarOtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 390, 50));

        FondoAgregarCarrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MostrarPedidos.png"))); // NOI18N
        getContentPane().add(FondoAgregarCarrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FondoBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BusquedaPR.png"))); // NOI18N
        getContentPane().add(FondoBuscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        FondoMostrarOpciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BusquedaPR2.png"))); // NOI18N
        getContentPane().add(FondoMostrarOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseClicked
        // TODO add your handling code here:
         mostrarPantalla2(); 
         if(!EscribirConsulta.getText().equals(null))
           InfoBusqueda.setText(EscribirConsulta.getText());
         else 
             System.out.println("ERROR");
        
        DefaultListModel restaurantes = new DefaultListModel();
        restaurantes.clear();
        consultasBaseDeDatos consulta = new BaseDeDatos();
        restaurantes = consulta.BuscarPalabrasClave(EscribirConsulta.getText());

        jList1.setModel(restaurantes); //Muestra los restaurantes que coinciden en la busqueda*/
       
    }//GEN-LAST:event_BotonBuscarMouseClicked

    private void InfoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoBusquedaActionPerformed

    private void BotonRealizarOtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRealizarOtraMouseClicked
        // TODO add your handling code here:
        //Boton realizar otra busqueda - MUESTRA PANTALLA 1
        inicioVentana();
    }//GEN-LAST:event_BotonRealizarOtraMouseClicked
   
    private void BotonVerRestauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerRestauranteMouseClicked
        
        mostrarPantalla3();
        
    }//GEN-LAST:event_BotonVerRestauranteMouseClicked

    private void BotonAtrasBusqAntMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasBusqAntMouseClicked
        //BOTON ATRAS BUSQUEDA ANTERIOR CUANDO ESTA EN EL CARRITO
        mostrarPantalla2();
    }//GEN-LAST:event_BotonAtrasBusqAntMouseClicked

    private void BotonAtrasP2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAtrasP2MouseClicked
        inicioVentana();
    }//GEN-LAST:event_BotonAtrasP2MouseClicked

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        
    }//GEN-LAST:event_jList1MouseClicked

    private void ConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmacionActionPerformed

    private void BotonAgregarPlatoCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgregarPlatoCCMouseClicked
        // SI AGREGAN UN PEDIDO
        
        Confirmacion.setVisible(true);
        BotonOk.setVisible(true);
    }//GEN-LAST:event_BotonAgregarPlatoCCMouseClicked

    private void BotonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonOkMouseClicked
        // TODO add your handling code here:
        Confirmacion.setVisible(false);
        BotonOk.setVisible(false);
    }//GEN-LAST:event_BotonOkMouseClicked

    
    public void transparenciaDelBoton(){
        BotonBuscar.setOpaque(false);
        BotonBuscar.setBackground(new Color(0,0,0,0));
        BotonRealizarOtra.setOpaque(false);
        BotonRealizarOtra.setBackground(new Color(0,0,0,0));
        BotonVerRestaurante.setOpaque(false);
        BotonVerRestaurante.setBackground(new Color(0,0,0,0));
        BotonAgregarPlatoCC.setOpaque(false);
        BotonAgregarPlatoCC.setBackground(new Color(0,0,0,0));
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaBusquedaPR().setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarPlatoCC;
    private javax.swing.JButton BotonAtrasBusqAnt;
    private javax.swing.JButton BotonAtrasP1;
    private javax.swing.JButton BotonAtrasP2;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonOk;
    private javax.swing.JButton BotonRealizarOtra;
    private javax.swing.JButton BotonVerRestaurante;
    private javax.swing.JTextField Confirmacion;
    private javax.swing.JTextField EscribirConsulta;
    private javax.swing.JLabel FondoAgregarCarrito;
    private javax.swing.JLabel FondoBuscador;
    private javax.swing.JLabel FondoMostrarOpciones;
    private javax.swing.JTextField InfoBusqueda;
    private javax.swing.JScrollPane ListaBusquedaRestaurantes;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
