/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author samyf
 */
public class PantallaInicialAdministrador extends javax.swing.JFrame {
    
    String usuario="";
    /**
     * Creates new form PantallaInicialAdministrador
     */
    public PantallaInicialAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
        public PantallaInicialAdministrador(String pUsuario) {
        initComponents();
        usuario=pUsuario;
        this.setLocationRelativeTo(null);
        this.jLabelMensajeInicial.setText(usuario);
    }
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCerrarSesion = new javax.swing.JButton();
        jLabelMensajeInicial = new javax.swing.JLabel();
        jButtonEliminarAdministracion = new javax.swing.JButton();
        jButtonCrearRestaurante = new javax.swing.JButton();
        jButtonModificarRestaurante = new javax.swing.JButton();
        jButtonEliminarRestaurante = new javax.swing.JButton();
        jButtonGestionarPerfil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCerrarSesion.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButtonCerrarSesion.setText("Cerrar Sesión");
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 120, -1));

        jLabelMensajeInicial.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        getContentPane().add(jLabelMensajeInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 140, 30));

        jButtonEliminarAdministracion.setText("Buscar restaurante");
        jButtonEliminarAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarAdministracionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 186, 145, -1));

        jButtonCrearRestaurante.setText("Crear restaurante");
        jButtonCrearRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearRestauranteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCrearRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 72, 145, -1));

        jButtonModificarRestaurante.setText("Modificar restaurante");
        jButtonModificarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarRestauranteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonModificarRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 110, 145, -1));

        jButtonEliminarRestaurante.setText("Eliminar restaurante");
        jButtonEliminarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarRestauranteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEliminarRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 148, 145, -1));

        jButtonGestionarPerfil.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButtonGestionarPerfil.setText("Gestionar perfil");
        jButtonGestionarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarPerfilActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGestionarPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IPantallaInicialAdministrador.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        InicioSesion iniciador= new InicioSesion();
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonEliminarAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarAdministracionActionPerformed
        // TODO add your handling code here:
        PantallaBuscarRestaurante iniciador = new PantallaBuscarRestaurante(usuario);
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEliminarAdministracionActionPerformed

    private void jButtonCrearRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearRestauranteActionPerformed
        PantallaCrearRestaurante iniciador = new PantallaCrearRestaurante();
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCrearRestauranteActionPerformed

    private void jButtonModificarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarRestauranteActionPerformed
        PantallaModificarRestaurante iniciador = new PantallaModificarRestaurante();
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonModificarRestauranteActionPerformed

    private void jButtonEliminarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarRestauranteActionPerformed
        PantallaEliminarRestaurante iniciador = new PantallaEliminarRestaurante();
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEliminarRestauranteActionPerformed

    private void jButtonGestionarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarPerfilActionPerformed
        PantallaGestionarAdmin iniciador = new PantallaGestionarAdmin(usuario);
        iniciador.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonGestionarPerfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicialAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonCrearRestaurante;
    private javax.swing.JButton jButtonEliminarAdministracion;
    private javax.swing.JButton jButtonEliminarRestaurante;
    private javax.swing.JButton jButtonGestionarPerfil;
    private javax.swing.JButton jButtonModificarRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMensajeInicial;
    // End of variables declaration//GEN-END:variables
}
