/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Color;

/**
 *
 * @author Tony
 */
public class PantallaPerfilDomiciliario extends javax.swing.JFrame {

    String usuariodom;

    /**
     * Creates new form PantallaPerfilDomiciliario
     */
    public PantallaPerfilDomiciliario() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jButtonAtrás.setOpaque(false);
        this.jButtonAtrás.setBackground(new Color(0, 0, 0, 0));
    }

    public PantallaPerfilDomiciliario(String pUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jButtonAtrás.setOpaque(false);
        this.jButtonAtrás.setBackground(new Color(0, 0, 0, 0));
        this.usuariodom = pUsuario;
        consultasBaseDeDatos consulta = new BaseDeDatos();
        ArrayList<Object> datosDomi = consulta.ObtenerDatosDomiciliario(pUsuario);
        int tam = datosDomi.size();
        for (int i = 0; i < tam; i++) {

            if (i == 0) {
                jTextFieldNombre.setText((String) datosDomi.get(i));
            }

            if (i == 1) {
                jTextFieldDocumento.setText((String) datosDomi.get(i));
            }

            if (i == 2) {
                jTextFieldTeléfono.setText((String) datosDomi.get(i));
            }

            if (i == 3) {
                jTextFieldDomiciliosEntregados.setText(String.valueOf(datosDomi.get(i)));
            }

            if (i == 4) {
                jTextFieldPlacaVehículo.setText((String) datosDomi.get(i));
            }

        }
        
        ImageIcon imagendomi = consulta.VerImagenDomiciliario(this.usuariodom);
        Icon icono = new ImageIcon(imagendomi.getImage().getScaledInstance(this.jLabelImagenDomi.getWidth(), this.jLabelImagenDomi.getHeight(), Image.SCALE_SMOOTH));
        this.jLabelImagenDomi.setIcon(icono);

        System.out.println(jTextFieldPlacaVehículo.getText());

        if (jTextFieldPlacaVehículo.getText().isEmpty() == true) {
            jButtonSolicitarVehículo.setVisible(true);
        } else {
            jButtonSolicitarVehículo.setVisible(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldDocumento = new javax.swing.JTextField();
        jTextFieldTeléfono = new javax.swing.JTextField();
        jTextFieldDomiciliosEntregados = new javax.swing.JTextField();
        jTextFieldPlacaVehículo = new javax.swing.JTextField();
        jButtonAtrás = new javax.swing.JButton();
        jButtonSolicitarVehículo = new javax.swing.JButton();
        jLabelImagenDomi = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setFocusable(false);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 250, 30));

        jTextFieldDocumento.setEditable(false);
        jTextFieldDocumento.setFocusable(false);
        getContentPane().add(jTextFieldDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, 250, 30));

        jTextFieldTeléfono.setEditable(false);
        jTextFieldTeléfono.setFocusable(false);
        jTextFieldTeléfono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTeléfonoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTeléfono, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 250, 30));

        jTextFieldDomiciliosEntregados.setEditable(false);
        jTextFieldDomiciliosEntregados.setFocusable(false);
        getContentPane().add(jTextFieldDomiciliosEntregados, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 490, 250, 30));

        jTextFieldPlacaVehículo.setEditable(false);
        jTextFieldPlacaVehículo.setFocusable(false);
        jTextFieldPlacaVehículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPlacaVehículoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldPlacaVehículo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 560, 250, 30));

        jButtonAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrásActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(689, 20, 70, 90));

        jButtonSolicitarVehículo.setText("Solicitar vehículo");
        jButtonSolicitarVehículo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitarVehículoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSolicitarVehículo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 560, -1, 30));
        getContentPane().add(jLabelImagenDomi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 90, 110));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaPerfilDomiciliario.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPlacaVehículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPlacaVehículoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPlacaVehículoActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldTeléfonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTeléfonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTeléfonoActionPerformed

    private void jButtonAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrásActionPerformed
        // TODO add your handling code here:
        PantallaInicialDomiciliario p = new PantallaInicialDomiciliario(usuariodom);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtrásActionPerformed

    private void jButtonSolicitarVehículoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitarVehículoActionPerformed
        // TODO add your handling code here:
        PantallaSolicitarVehículo p = new PantallaSolicitarVehículo(usuariodom);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSolicitarVehículoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfilDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfilDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfilDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPerfilDomiciliario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPerfilDomiciliario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtrás;
    private javax.swing.JButton jButtonSolicitarVehículo;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagenDomi;
    private javax.swing.JTextField jTextFieldDocumento;
    private javax.swing.JTextField jTextFieldDomiciliosEntregados;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPlacaVehículo;
    private javax.swing.JTextField jTextFieldTeléfono;
    // End of variables declaration//GEN-END:variables
}
