/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
/**
 *
 * @author Estefania
 */
public class PantallaClientesActivos extends javax.swing.JFrame {
    
 
    String nRestaurante;
    ArrayList<String> clientesActivos = new ArrayList<>();
    
    public PantallaClientesActivos() {
        initComponents();
        transparenciaDelBoton();  
        this.setLocationRelativeTo(null);   
    }
     public PantallaClientesActivos(String pRestaurante) {
        initComponents();
        transparenciaDelBoton();
        nRestaurante = pRestaurante;
        mostrarInformacionClientes();
        this.setLocationRelativeTo(null);   
    }
    
    /*funcion para agregar icono del programa*/
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }
    
    public void transparenciaDelBoton(){
        BotonAtras.setOpaque(false);
        BotonAtras.setBackground(new Color(0,0,0,0));
    }
    
    public void mostrarInformacionClientes(){
        
        consultasBaseDeDatos consulta = new BaseDeDatos();
        ArrayList<String> nombres = new ArrayList<>();
        DefaultListModel clientesA = new DefaultListModel<>();
        nombres = consulta.darClientesActivos(nRestaurante);
        
        int conta = 0;
        
        
        for(int i = 0; i < nombres.size(); i++){
            
            if(!(validarExistencia(nombres.get(i)))){ // verifica si ya esta en la lista 
               
              for(int j = 0; j < nombres.size();j++){ // hace el conteo de pedidos
                  if(nombres.get(i) == nombres.get(j)){
                      conta++;
                  }
              }  
            }
            
            if(conta >= 2){ // Si ha realizado mas de dos pedidos en el restaurante
                clientesActivos.add(nombres.get(i));
                clientesA.addElement(nombres.get(i));
                conta = 0;
            }
        }
        
       
        
        listaClientesAct.setModel(clientesA); //Muestra la lista de clientes activos
        
    }
    
    public boolean validarExistencia(String nombre){
        
        boolean resp = false;
        for(int i = 0; i< clientesActivos.size();i++){
            if(clientesActivos.get(i).equals(nombre)){
                resp = true;
                break;
            }
        }
        
        return resp;
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaClientesAct = new javax.swing.JList<>();
        BotonAtras = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaClientesAct.setBackground(new java.awt.Color(255, 254, 251));
        listaClientesAct.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        listaClientesAct.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaClientesAct);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 410, 410));
        getContentPane().add(BotonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 60));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ClientesActivosR.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaClientesActivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaClientesActivos().setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JLabel Fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaClientesAct;
    // End of variables declaration//GEN-END:variables
}
