/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Hernández Guerrero
 */
public class PantallaCrearRestaurante extends javax.swing.JFrame 
{
    String usuario = "";
    /**
     * Creates new form CrearRestaurante
     */
    public PantallaCrearRestaurante() 
    {
        initComponents();
        Transparencia();
        this.setLocationRelativeTo(null);
    }
    
    public PantallaCrearRestaurante(String usuario) 
    {
        initComponents();
        Transparencia();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
    }
    
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaCampoDescripcion = new javax.swing.JTextArea();
        jTextFieldCampoImagen = new javax.swing.JTextField();
        jTextFieldCampoNIT = new javax.swing.JTextField();
        jTextFieldCampoCostoDeEnvio = new javax.swing.JTextField();
        jTextFieldCampoPassword = new javax.swing.JTextField();
        jTextFieldCampoDireccion = new javax.swing.JTextField();
        jTextFieldCampoPalabrasClave = new javax.swing.JTextField();
        jTextFieldCampoNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setMaximumSize(new java.awt.Dimension(800, 690));
        setMinimumSize(new java.awt.Dimension(800, 690));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextAreaCampoDescripcion.setColumns(20);
        jTextAreaCampoDescripcion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaCampoDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 450, 60));

        jTextFieldCampoImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoImagenActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 255, -1));

        jTextFieldCampoNIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoNITActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 190, -1));

        jTextFieldCampoCostoDeEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoCostoDeEnvioActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoCostoDeEnvio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 190, -1));

        jTextFieldCampoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 190, -1));

        jTextFieldCampoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 190, -1));

        jTextFieldCampoPalabrasClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoPalabrasClaveActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoPalabrasClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 610, 450, -1));

        jTextFieldCampoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCampoNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldCampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 190, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaCrearRestaurante.png"))); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 50, 50));

        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 60, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCampoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoNombreActionPerformed

    }//GEN-LAST:event_jTextFieldCampoNombreActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        PantallaInicialAdministrador pantallaGestion = new PantallaInicialAdministrador(usuario);
        pantallaGestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if(this.jTextFieldCampoNombre.getText().isEmpty() || this.jTextFieldCampoPassword.getText().isEmpty()|| this.jTextFieldCampoNIT.getText().isEmpty() || this.jTextAreaCampoDescripcion.getText().isEmpty() || this.jTextFieldCampoCostoDeEnvio.getText().isEmpty() || this.jTextFieldCampoImagen.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Hay un campo vacio.");
        }
        else if (consulta.ValidarExistenciaRestaurante(this.jTextFieldCampoNombre.getText()))
        {
            JOptionPane.showMessageDialog(null, "El restaurante ya existe.");
            PantallaCrearRestaurante pantallaGestion = new PantallaCrearRestaurante(usuario);
            pantallaGestion.setVisible(true);
            this.dispose();
        }
        else
        {
            float costoDeEnvio = Float.parseFloat(this.jTextFieldCampoCostoDeEnvio.getText());
            resultado = consulta.CrearRestaurante(this.jTextFieldCampoNombre.getText(), this.jTextFieldCampoPassword.getText(), this.jTextFieldCampoNIT.getText(), this.jTextFieldCampoDireccion.getText(), this.jTextAreaCampoDescripcion.getText(), costoDeEnvio, this.jTextFieldCampoImagen.getText());
            consulta.AlmacenarPalabrasClave (this.jTextFieldCampoNombre.getText(), this.jTextFieldCampoPalabrasClave.getText());
            PantallaAgregarPlato pantallaGestion = new PantallaAgregarPlato(jTextFieldCampoNombre.getText());
            pantallaGestion.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jTextFieldCampoNITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoNITActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoNITActionPerformed

    private void jTextFieldCampoCostoDeEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoCostoDeEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoCostoDeEnvioActionPerformed

    private void jTextFieldCampoImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoImagenActionPerformed

    private void jTextFieldCampoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoPasswordActionPerformed

    private void jTextFieldCampoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoDireccionActionPerformed

    private void jTextFieldCampoPalabrasClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCampoPalabrasClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCampoPalabrasClaveActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void Transparencia ()
    {
        jTextFieldCampoNombre.setOpaque(false);
        jTextFieldCampoNombre.setBackground(new Color(0, 0, 0, 0));
        jTextFieldCampoPassword.setOpaque(false);
        jTextFieldCampoPassword.setBackground(new Color(0, 0, 0, 0));
        jTextFieldCampoNIT.setOpaque(false);
        jTextFieldCampoNIT.setBackground(new Color(0, 0, 0, 0));
        jTextFieldCampoDireccion.setOpaque(false);
        jTextFieldCampoDireccion.setBackground(new Color(0, 0, 0, 0));
        jTextAreaCampoDescripcion.setOpaque(false);
        jTextAreaCampoDescripcion.setBackground(new Color(0, 0, 0, 0));
        jTextFieldCampoCostoDeEnvio.setOpaque(false);
        jTextFieldCampoCostoDeEnvio.setBackground(new Color(0, 0, 0, 0));
        jTextFieldCampoPalabrasClave.setOpaque(false);
        jTextFieldCampoPalabrasClave.setBackground(new Color(0, 0, 0, 0));
        jButtonAceptar.setOpaque(false);
        jButtonAceptar.setBackground(new Color(0, 0, 0, 0));
        jButtonCancelar.setOpaque(false);
        jButtonCancelar.setBackground(new Color(0, 0, 0, 0));
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCrearRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCrearRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaCampoDescripcion;
    private javax.swing.JTextField jTextFieldCampoCostoDeEnvio;
    private javax.swing.JTextField jTextFieldCampoDireccion;
    private javax.swing.JTextField jTextFieldCampoImagen;
    private javax.swing.JTextField jTextFieldCampoNIT;
    private javax.swing.JTextField jTextFieldCampoNombre;
    private javax.swing.JTextField jTextFieldCampoPalabrasClave;
    private javax.swing.JTextField jTextFieldCampoPassword;
    // End of variables declaration//GEN-END:variables
}
