/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;
import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.time.LocalDateTime;
import java.util.Date;

/**
 *
 * @author Tony
 */
public class PantallaSatisfacción extends javax.swing.JFrame {

    String prestaurante;
    String pdomiciliario;
    String clientep;
    int pedidoid;

    /**
     * Creates new form PantallaSatisfacción
     */
    public PantallaSatisfacción() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jButtonAtras.setOpaque(false);
        this.jButtonAtras.setBackground(new Color(0, 0, 0, 0));
        this.jButtonEnviar.setOpaque(false);
        this.jButtonEnviar.setBackground(new Color(0, 0, 0, 0));
    }

    public PantallaSatisfacción(int idpedido, String restaurante, String domi, String cliente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jButtonAtras.setOpaque(false);
        this.jButtonAtras.setBackground(new Color(0, 0, 0, 0));
        this.jButtonEnviar.setOpaque(false);
        this.jButtonEnviar.setBackground(new Color(0, 0, 0, 0));
        this.prestaurante = restaurante;
        this.pdomiciliario = domi;
        this.clientep = cliente;
        this.pedidoid = idpedido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButtonEnviar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        jComboBox3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jComboBox3.setMaximumRowCount(5);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4", "5" }));
        jComboBox3.setToolTipText("");
        jComboBox3.setAlignmentX(1.0F);
        jComboBox3.setAlignmentY(1.0F);
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jComboBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 690));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox1.setMaximumRowCount(6);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4", "5" }));
        jComboBox1.setToolTipText("");
        jComboBox1.setAlignmentX(1.0F);
        jComboBox1.setAlignmentY(1.0F);
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, 20));

        jComboBox4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jComboBox4.setMaximumRowCount(6);
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "1", "2", "3", "4", "5" }));
        jComboBox4.setToolTipText("");
        jComboBox4.setAlignmentX(1.0F);
        jComboBox4.setAlignmentY(1.0F);
        jComboBox4.setBorder(null);
        jComboBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, 410, 130));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 410, 130));

        jButtonEnviar.setBackground(new java.awt.Color(240, 0, 0));
        jButtonEnviar.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jButtonEnviar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEnviar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 580, 100, 40));

        jButtonAtras.setBackground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jButtonAtras.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAtras.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaSatisfaccion.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarActionPerformed

        if (this.jComboBox1.getSelectedItem() == "Seleccionar" && this.jComboBox4.getSelectedItem() != "Seleccionar") {
            JOptionPane.showMessageDialog(null, "Por favor seleccione la calificacion para restaurante");
        }
        if (this.jComboBox4.getSelectedItem() == "Seleccionar" && this.jComboBox1.getSelectedItem() != "Seleccionar") {
            JOptionPane.showMessageDialog(null, "Por favor seleccione la calificacion para domiciliario");
        }
        if (this.jComboBox1.getSelectedItem() == "Seleccionar" && this.jComboBox4.getSelectedItem() == "Seleccionar") {
            JOptionPane.showMessageDialog(null, "Por favor seleccione la calificacion para restaurante y domiciliario");
        }
        if (this.jComboBox1.getSelectedItem() != "Seleccionar" && this.jComboBox4.getSelectedItem() != "Seleccionar") {
            
            String fecha;
            LocalDateTime registro = LocalDateTime.now();
            int dia,mes,year;
            dia = registro.getDayOfMonth();
            mes = registro.getMonthValue();
            year = registro.getYear();
            fecha = dia+"/"+mes+"/"+year;
            System.out.println("fecha actual  "+ fecha);
            
            
            consultasBaseDeDatos consulta = new BaseDeDatos();
            
            //ver si tiene fecha el pedido, si no tiene se pone la fecha actual, si tiene se comparan
            String fechaResena = consulta.darHoraResena(pedidoid);
            String fechaResena2 = consulta.darHoraResena2(pedidoid);
            System.out.println("fecha reseña " +  fechaResena);
            System.out.println("fecha reseña 2 " +  fechaResena2);
            if (fechaResena == null && fechaResena2 == null)
            {
              // se crea normalmente
                System.out.println("se crea normalmente");
                consulta.calificarRestaurante(pedidoid, clientep, prestaurante, Integer.parseInt(this.jComboBox1.getSelectedItem().toString()),this.jTextArea2.getText() , fecha);
                consulta.calificarDomiciliario(pedidoid, clientep, pdomiciliario, Integer.parseInt(this.jComboBox1.getSelectedItem().toString()),this.jTextArea2.getText() , fecha);
                JOptionPane.showMessageDialog(null, "Gracias por sus calificaciones");
                PantallaVerPedidos p = new PantallaVerPedidos(clientep);
                p.setVisible(true);
                this.dispose();
            }
            else
            {
                System.out.println("antes de verificar diferencia de fechas");
                String[] partes = fechaResena.split("/");
                String[] partes2 = fechaResena2.split("/");
                if( partes[0].equals(  Integer.toString(dia)  ) && partes[1].equals(  Integer.toString(mes)  ) && partes[2].equals(  Integer.toString(year)  ) &&
                    partes2[0].equals(  Integer.toString(dia)  ) && partes2[1].equals(  Integer.toString(mes)  ) && partes2[2].equals(  Integer.toString(year)  )    ){
                    System.out.println("se crea por la fecha");
                    consulta.calificarRestauranteAc(pedidoid, clientep, prestaurante, Integer.parseInt(this.jComboBox1.getSelectedItem().toString()),this.jTextArea2.getText() , fecha);
                    consulta.calificarDomiciliarioAc(pedidoid, clientep, pdomiciliario, Integer.parseInt(this.jComboBox1.getSelectedItem().toString()),this.jTextArea2.getText() , fecha);
                    JOptionPane.showMessageDialog(null, "Gracias por sus calificaciones");
                    PantallaVerPedidos p = new PantallaVerPedidos(clientep);
                    p.setVisible(true);
                    this.dispose();
                }
                else
                {
                    System.out.println("no se pudo");
                    JOptionPane.showMessageDialog(null, "ya no puede modificar su calificacion");
                    PantallaVerPedidos p = new PantallaVerPedidos(clientep);
                    p.setVisible(true);
                    this.dispose();
                }
            }
        }

    }//GEN-LAST:event_jButtonEnviarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        
        PantallaVerPedidos p = new PantallaVerPedidos(clientep);
        p.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaSatisfacción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaSatisfacción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaSatisfacción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaSatisfacción.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaSatisfacción().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonEnviar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
