/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Hernández Guerrero
 */
public class PantallaModificarRestaurante extends javax.swing.JFrame {
    String usuario = "";
    /**
     * Creates new form PantallaModificarPlato
     */
    public PantallaModificarRestaurante() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public PantallaModificarRestaurante(String usuario)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonModImagen1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombreRestaurante = new javax.swing.JTextField();
        jButtonModNombre = new javax.swing.JButton();
        jButtonModDireccion = new javax.swing.JButton();
        jButtonModDescripcion = new javax.swing.JButton();
        jButtonModCostoDeEnvio = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jTextFieldModNombre = new javax.swing.JTextField();
        jTextFieldModDireccion = new javax.swing.JTextField();
        jTextFieldModDescripcion = new javax.swing.JTextField();
        jTextFieldModCostoDeEnvio = new javax.swing.JTextField();
        jButtonModImagen = new javax.swing.JButton();
        jTextFieldModImagen = new javax.swing.JTextField();

        jButtonModImagen1.setText("Modificar costo de envío");
        jButtonModImagen1.setToolTipText("");
        jButtonModImagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModImagen1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jLabel1.setText("Modificar restaurante");

        jLabel2.setText("Nombre del restaurante");

        jButtonModNombre.setText("Modificar nombre");
        jButtonModNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModNombreActionPerformed(evt);
            }
        });

        jButtonModDireccion.setText("Modificar dirección");
        jButtonModDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModDireccionActionPerformed(evt);
            }
        });

        jButtonModDescripcion.setText("Modificar descripción");
        jButtonModDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModDescripcionActionPerformed(evt);
            }
        });

        jButtonModCostoDeEnvio.setText("Modificar costo de envío");
        jButtonModCostoDeEnvio.setToolTipText("");
        jButtonModCostoDeEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModCostoDeEnvioActionPerformed(evt);
            }
        });

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jTextFieldModNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModNombreActionPerformed(evt);
            }
        });

        jButtonModImagen.setText("Modificar imagen");
        jButtonModImagen.setToolTipText("");
        jButtonModImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModImagenActionPerformed(evt);
            }
        });

        jTextFieldModImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModImagenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAtras))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldNombreRestaurante))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButtonModCostoDeEnvio, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(jButtonModDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldModCostoDeEnvio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldModDescripcion))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldModNombre)
                                    .addComponent(jTextFieldModDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonModImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldModImagen)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButtonAtras))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNombreRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModNombre)
                    .addComponent(jTextFieldModNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModDireccion)
                    .addComponent(jTextFieldModDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModDescripcion)
                    .addComponent(jTextFieldModDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModCostoDeEnvio)
                    .addComponent(jTextFieldModCostoDeEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldModImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModImagen))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModDireccionActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if (this.jTextFieldModDireccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo está vacio.");
        }
        else
        {
            resultado = consulta.ModificarDireccionRestaurante(this.jTextFieldNombreRestaurante.getText(), this.jTextFieldModDireccion.getText());
        } 
    }//GEN-LAST:event_jButtonModDireccionActionPerformed

    private void jButtonModNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModNombreActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if (this.jTextFieldModNombre.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El campo está vacio.");
        }
        else
        {
            resultado = consulta.ModificarNombreRestaurante(this.jTextFieldNombreRestaurante.getText(), this.jTextFieldModNombre.getText());
        } 
    }//GEN-LAST:event_jButtonModNombreActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        PantallaInicialAdministrador pantallaGestion = new PantallaInicialAdministrador(usuario);
        pantallaGestion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonModDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModDescripcionActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if (this.jTextFieldModDescripcion.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El campo está vacio.");
        }
        else
        {
            resultado = consulta.ModificarDescripcionPlato(this.jTextFieldNombreRestaurante.getText(), this.jTextFieldModDescripcion.getText());
        }        
    }//GEN-LAST:event_jButtonModDescripcionActionPerformed

    private void jButtonModCostoDeEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModCostoDeEnvioActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if (this.jTextFieldModCostoDeEnvio.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El campo está vacio.");
        }
        else
        {
            resultado = consulta.ModificarImagenPlato(this.jTextFieldNombreRestaurante.getText(), this.jTextFieldModCostoDeEnvio.getText());
        }       
    }//GEN-LAST:event_jButtonModCostoDeEnvioActionPerformed

    private void jButtonModImagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModImagen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModImagen1ActionPerformed

    private void jButtonModImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModImagenActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if(this.jTextFieldModImagen.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "El campo está vacio.");
        }
        else
        {
            resultado = consulta.ModificarImagenRestaurante(this.jTextFieldNombreRestaurante.getText(), this.jTextFieldModImagen.getText());
        }      
    }//GEN-LAST:event_jButtonModImagenActionPerformed

    private void jTextFieldModNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModNombreActionPerformed

    private void jTextFieldModImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModImagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModImagenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonModCostoDeEnvio;
    private javax.swing.JButton jButtonModDescripcion;
    private javax.swing.JButton jButtonModDireccion;
    private javax.swing.JButton jButtonModImagen;
    private javax.swing.JButton jButtonModImagen1;
    private javax.swing.JButton jButtonModNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldModCostoDeEnvio;
    private javax.swing.JTextField jTextFieldModDescripcion;
    private javax.swing.JTextField jTextFieldModDireccion;
    private javax.swing.JTextField jTextFieldModImagen;
    private javax.swing.JTextField jTextFieldModNombre;
    private javax.swing.JTextField jTextFieldNombreRestaurante;
    // End of variables declaration//GEN-END:variables
}
