/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gato
 */
public class PantallaModificarCliente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaModificarCliente
     */
    public PantallaModificarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciaDelBoton();
        
    }
    
    public PantallaModificarCliente(String usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        LabelNombreUsuario.setText(usuario);
        transparenciaDelBoton();
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelNombreUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TF_ModificarNombreCliente = new javax.swing.JTextField();
        BotonModificarNombreCliente = new javax.swing.JButton();
        TF_ModificarApellidoCliente = new javax.swing.JTextField();
        BotonModificarApellidoCliente = new javax.swing.JButton();
        TF_ModificarDireccionCliente = new javax.swing.JTextField();
        BotonModificarDireccionCliente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BotonEliminarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LabelNombreUsuario.setText("Nombre de usuario");
        getContentPane().add(LabelNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 400, 30));

        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarPantallaInicialCliente(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 623, 110, 60));

        TF_ModificarNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_ModificarNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(TF_ModificarNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 180, 450, 50));

        BotonModificarNombreCliente.setBorder(null);
        BotonModificarNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarNombreClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonModificarNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 173, 120, 60));
        getContentPane().add(TF_ModificarApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 270, 450, 60));

        BotonModificarApellidoCliente.setBorder(null);
        BotonModificarApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarApellidoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonModificarApellidoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 273, 120, 60));
        getContentPane().add(TF_ModificarDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 370, 450, 60));

        BotonModificarDireccionCliente.setBorder(null);
        BotonModificarDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarDireccionClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonModificarDireccionCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 373, 120, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/modificarCliente.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BotonEliminarCliente.setBorder(null);
        BotonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 613, 180, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarPantallaInicialCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarPantallaInicialCliente
        // TODO add your handling code here:
        PantallaInicialCliente pantalla = new PantallaInicialCliente(LabelNombreUsuario.getText());
                    pantalla.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_BotonRegresarPantallaInicialCliente

    private void TF_ModificarNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_ModificarNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ModificarNombreClienteActionPerformed

    private void BotonModificarNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarNombreClienteActionPerformed
        // TODO add your handling code here:
        
        if(TF_ModificarNombreCliente.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Error al Modificar la dirección del cliente");
            return;
        }
        
        consultasBaseDeDatos consulta = new BaseDeDatos();
        if(consulta.ModificarNombreCliente(LabelNombreUsuario.getText(), TF_ModificarNombreCliente.getText()))
        {
                    JOptionPane.showMessageDialog(null, "Se modifico el nombre del cliente con exito");
                    TF_ModificarNombreCliente.setText("");
        }
        else
        {
            TF_ModificarNombreCliente.setText("");
            JOptionPane.showMessageDialog(null, "Error al Modificar el nombre del cliente");
        }
        
        
        
        
    }//GEN-LAST:event_BotonModificarNombreClienteActionPerformed

    private void BotonModificarApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarApellidoClienteActionPerformed
        // TODO add your handling code here:
        
        if(TF_ModificarApellidoCliente.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Error al Modificar la dirección del cliente");
            return;
        }
        
        consultasBaseDeDatos consulta = new BaseDeDatos();
        if(consulta.ModificarApellidoCliente(LabelNombreUsuario.getText(), TF_ModificarApellidoCliente.getText()))
        {
                    JOptionPane.showMessageDialog(null, "Se modifico el apellido del cliente con exito");
                    TF_ModificarApellidoCliente.setText("");
        }
        else
        {
            TF_ModificarNombreCliente.setText("");
            JOptionPane.showMessageDialog(null, "Error al Modificar el apellido del cliente");
        }
        
        
    }//GEN-LAST:event_BotonModificarApellidoClienteActionPerformed

    private void BotonModificarDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarDireccionClienteActionPerformed
        // TODO add your handling code here:
        
        if(TF_ModificarDireccionCliente.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Error al Modificar la dirección del cliente");
            return;
        }
        
        consultasBaseDeDatos consulta = new BaseDeDatos();
        
        
        if(consulta.ModificarDireccionCliente(LabelNombreUsuario.getText(), TF_ModificarDireccionCliente.getText()))
        {
                    JOptionPane.showMessageDialog(null, "Se modifico la dirección del cliente con exito");
                    TF_ModificarDireccionCliente.setText("");
        }
        else
        {
            TF_ModificarNombreCliente.setText("");
            JOptionPane.showMessageDialog(null, "Error al Modificar la dirección del cliente");
        }
    }//GEN-LAST:event_BotonModificarDireccionClienteActionPerformed

    private void BotonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarClienteActionPerformed
        // TODO add your handling code here:
         consultasBaseDeDatos consulta = new BaseDeDatos();
         
         if(consulta.VaciarCarrito(LabelNombreUsuario.getText()))
         {
             
             if(consulta.EliminarPedido(LabelNombreUsuario.getText()))
             {
                 if(consulta.EliminarCliente(LabelNombreUsuario.getText()))
                 {
                     if(consulta.EliminarCuenta(LabelNombreUsuario.getText(), "C"))
                       {
                          JOptionPane.showMessageDialog(null, "Se elimino la cuenta con exito");
                     
                            InicioSesion pantalla = new InicioSesion();
                            pantalla.setVisible(true);
                            this.dispose();

                         }
                         else
                         {
                             JOptionPane.showMessageDialog(null, "Error al eliminar cuenta");
                         }
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Error al eliminar el cliente");
                }
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Error al eliminar los pedidos");
             }
             
         }
         else
         {
             JOptionPane.showMessageDialog(null, "Error al eliminar el carrito de compras");
         }
        
        
    }//GEN-LAST:event_BotonEliminarClienteActionPerformed

    public void transparenciaDelBoton(){
        BotonModificarNombreCliente.setOpaque(false);
        BotonModificarNombreCliente.setBackground(new Color(0,0,0,0));
        
        BotonModificarApellidoCliente.setOpaque(false);
        BotonModificarApellidoCliente.setBackground(new Color(0,0,0,0));
        
        BotonModificarDireccionCliente.setOpaque(false);
        BotonModificarDireccionCliente.setBackground(new Color(0,0,0,0));
        
        jButton1.setOpaque(false);
        jButton1.setBackground(new Color(0,0,0,0));
        
        BotonEliminarCliente.setOpaque(false);
        BotonEliminarCliente.setBackground(new Color(0,0,0,0));
        
     
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEliminarCliente;
    private javax.swing.JButton BotonModificarApellidoCliente;
    private javax.swing.JButton BotonModificarDireccionCliente;
    private javax.swing.JButton BotonModificarNombreCliente;
    private javax.swing.JLabel LabelNombreUsuario;
    private javax.swing.JTextField TF_ModificarApellidoCliente;
    private javax.swing.JTextField TF_ModificarDireccionCliente;
    private javax.swing.JTextField TF_ModificarNombreCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
