/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Camilo Hernández Guerrero
 */
public class PantallaEliminarRestaurante extends javax.swing.JFrame
{
    String usuario = "";
    /**
     * Creates new form PantallaEliminarPlato
     */
    public PantallaEliminarRestaurante() 
    {
        initComponents();
        Transparencia();
        this.setLocationRelativeTo(null);
    }
    
    public PantallaEliminarRestaurante(String usuario) 
    {
        initComponents();
        Transparencia();
        this.setLocationRelativeTo(null);
        this.usuario = usuario;
    }
        /*funcion para agregar icono del programa*/
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreRestaurante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombreRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreRestauranteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 460, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaEliminarRestaurante.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 630, 50, 50));

        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 50, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreRestauranteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreRestauranteActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        PantallaInicialAdministrador pantallaGestion = new PantallaInicialAdministrador(usuario);
        pantallaGestion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado = false;
        
        if(this.jTextFieldNombreRestaurante.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "No se ha indicado un nombre.");
        }
        else if (!consulta.ValidarExistenciaRestaurante(this.jTextFieldNombreRestaurante.getText()))
        {
            JOptionPane.showMessageDialog(null, "El restaurante no existe.");
            PantallaEliminarRestaurante pantallaGestion = new PantallaEliminarRestaurante(usuario);
            pantallaGestion.setVisible(true);
            this.dispose();
        }
        else
        {
            resultado = consulta.EliminarRestaurante(this.jTextFieldNombreRestaurante.getText());
            PantallaInicialAdministrador pantallaGestion = new PantallaInicialAdministrador(usuario);
            pantallaGestion.setVisible(true);
            this.dispose();
        }
        
        
    }//GEN-LAST:event_jButtonAceptarActionPerformed
       
    
    public void Transparencia ()
    {
        jTextFieldNombreRestaurante.setOpaque(false);
        jTextFieldNombreRestaurante.setBackground(new Color(0, 0, 0, 0));
        jButtonAceptar.setOpaque(false);
        jButtonAceptar.setBackground(new Color(0, 0, 0, 0));
        jButtonCancelar.setOpaque(false);
        jButtonCancelar.setBackground(new Color(0, 0, 0, 0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaEliminarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaEliminarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaEliminarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaEliminarRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaEliminarRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextFieldNombreRestaurante;
    // End of variables declaration//GEN-END:variables
}
