/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import javax.swing.JOptionPane;
import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;

/**
 *
 * @author Tony
 */
public class PantallaInconveniente extends javax.swing.JFrame {

    int pedidoid;
    String userdomi;

    /**
     * Creates new form PantallaSolicitarVehículo
     */
    public PantallaInconveniente() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setLocationRelativeTo(null);
        this.jButtonAtrás.setOpaque(false);
        this.jButtonAtrás.setBackground(new Color(0, 0, 0, 0));
        this.jButtonReportar.setOpaque(false);
        this.jButtonReportar.setBackground(new Color(0, 0, 0, 0));
    }

    public PantallaInconveniente(int pedido, String userdom) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jButtonAtrás.setOpaque(false);
        this.jButtonAtrás.setBackground(new Color(0, 0, 0, 0));
        this.jButtonReportar.setOpaque(false);
        this.jButtonReportar.setBackground(new Color(0, 0, 0, 0));
        this.pedidoid = pedido;
        this.userdomi = userdom;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReportar = new javax.swing.JButton();
        jButtonAtrás = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTextoInconveniente = new javax.swing.JTextArea();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReportar.setBorder(null);
        jButtonReportar.setContentAreaFilled(false);
        jButtonReportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReportarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 260, 50));

        jButtonAtrás.setBorder(null);
        jButtonAtrás.setContentAreaFilled(false);
        jButtonAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrásActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, 70));

        jTextAreaTextoInconveniente.setColumns(20);
        jTextAreaTextoInconveniente.setRows(5);
        jScrollPane1.setViewportView(jTextAreaTextoInconveniente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 489, 240));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaInconveniente.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrásActionPerformed
        // TODO add your handling code here:
        PantallaPedidosEnCursoDomiciliario p = new PantallaPedidosEnCursoDomiciliario(this.userdomi);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtrásActionPerformed

    private void jButtonReportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReportarActionPerformed
        // TODO add your handling code here:
        consultasBaseDeDatos consulta = new BaseDeDatos();
        String cliente = consulta.ObtenerClienteDomicilio(pedidoid);
        String restaurante = consulta.ObtenerRestauranteDomicilio(pedidoid);
        String mensaje = this.jTextAreaTextoInconveniente.getText();
        if (mensaje == null) {
            JOptionPane.showMessageDialog(null, "Por favor describa el inconveniente");
        } else {
            boolean validar = consulta.CrearInconveniente(cliente, restaurante, mensaje, this.pedidoid, this.userdomi);
            if (validar == true) {
                JOptionPane.showMessageDialog(null, "El inconveniente fue reportado correctamente");
                PantallaPedidosEnCursoDomiciliario p = new PantallaPedidosEnCursoDomiciliario(this.userdomi);
                p.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error, por favor intentelo de nuevo");
            }
        }
    }//GEN-LAST:event_jButtonReportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInconveniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInconveniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInconveniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInconveniente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInconveniente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtrás;
    private javax.swing.JButton jButtonReportar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaTextoInconveniente;
    // End of variables declaration//GEN-END:variables
}
