/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import Modelo.CorreoElectronico;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.swing.JOptionPane;

/**
 *
 * @author samyf
 */
public class PantallaRecuperarContrasena extends javax.swing.JFrame {

    /**
     * Creates new form PantallaRecuperarContrasena
     */
    int codigo;
    String pUsuario;
    public PantallaRecuperarContrasena() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.codigo=(int) Math.floor(Math.random()*(999999-1000+1)+1000);
        this.Transparencia();
        
    }
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonEnviarCorreo = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonVerificar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(800, 690));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 201, 30));

        jButtonEnviarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEnviarCorreoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEnviarCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 295, 180, 50));
        getContentPane().add(jTextFieldCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 201, 30));

        jButtonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 525, 200, 50));

        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 120, 50));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IPantallaRecuperarContrasena.png"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEnviarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEnviarCorreoActionPerformed
        // TODO add your handling code here:
        
        CorreoElectronico nuevo = new CorreoElectronico();
        consultasBaseDeDatos consulta= new BaseDeDatos();
        boolean seguir= false;
       
        if(!this.jTextFieldUsuario.getText().isEmpty())
        {
            try {
                  pUsuario=this.jTextFieldUsuario.getText();
                  seguir = nuevo.enviarCorreoRecuperar(this.codigo,consulta.ObtenerCorreo(this.jTextFieldUsuario.getText()) );
                  
                } catch (MessagingException ex) {
                     Logger.getLogger(InicioSesion.class.getName()).log(Level.SEVERE, null, ex);
                }
            if(!seguir)
            {
                JOptionPane.showMessageDialog(null, "Usuario no existe");
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo Usuario vacío");
        }
        
        
    }//GEN-LAST:event_jButtonEnviarCorreoActionPerformed

    private void jButtonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarActionPerformed
        // TODO add your handling code here:
        if(!this.jTextFieldCodigo.getText().isEmpty() && this.jTextFieldCodigo.getText().equals(Integer.toString(this.codigo)))
        {
            JOptionPane.showMessageDialog(null, "Código de seguridad correcto");
            PantallaCambioContrasenaRecuperacion iniciador=new PantallaCambioContrasenaRecuperacion(pUsuario);
            iniciador.setVisible(true);
            this.dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo código de seguridad vacío");
        }
    }//GEN-LAST:event_jButtonVerificarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        InicioSesion iniciador= new InicioSesion();
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    
    private void Transparencia()
    {
        this.jButtonEnviarCorreo.setOpaque(false);
        this.jButtonEnviarCorreo.setBackground(new Color(0, 0, 0, 0));
        this.jButtonEnviarCorreo.setBorderPainted(false);
        this.jButtonSalir.setOpaque(false);
        this.jButtonSalir.setBackground(new Color(0, 0, 0, 0));
        this.jButtonSalir.setBorderPainted(false);
        this.jButtonVerificar.setOpaque(false);
        this.jButtonVerificar.setBackground(new Color(0, 0, 0, 0));
        this.jButtonVerificar.setBorderPainted(false);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaRecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaRecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaRecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaRecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRecuperarContrasena().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEnviarCorreo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonVerificar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
