/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author samyf
 */
public class PantallaModificarAdmin extends javax.swing.JFrame {

    /**
     * Creates new form ModificarAdmin
     */
    String Usuario;
    
    public PantallaModificarAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.jTextFieldCampoUsuario.setText(Usuario);
    }
        public PantallaModificarAdmin(String pUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        Usuario=pUsuario;
    }
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLabelMensajeInicial = new javax.swing.JLabel();
        jLabelEtiquetaUsuario = new javax.swing.JLabel();
        jLabelEtiquetaContrasena = new javax.swing.JLabel();
        jTextFieldCampoUsuario = new javax.swing.JTextField();
        jPasswordFieldCampoContrasena = new javax.swing.JPasswordField();
        jButtonModificarUsuario = new javax.swing.JButton();
        jButtonModificarContrasena = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelMensajeInicial.setText("Modificar Usuario");

        jLabelEtiquetaUsuario.setText("Usuario");

        jLabelEtiquetaContrasena.setText("Contraseña");

        jButtonModificarUsuario.setText("Modificar");
        jButtonModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarUsuarioActionPerformed(evt);
            }
        });

        jButtonModificarContrasena.setText("Modificar");
        jButtonModificarContrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarContrasenaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonSalir))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEtiquetaUsuario)
                    .addComponent(jLabelEtiquetaContrasena))
                .addGap(94, 94, 94)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCampoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabelMensajeInicial)
                    .addComponent(jPasswordFieldCampoContrasena))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonModificarUsuario)
                    .addComponent(jButtonModificarContrasena))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMensajeInicial)
                        .addGap(45, 45, 45)
                        .addComponent(jLabelEtiquetaUsuario))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCampoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonModificarUsuario)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEtiquetaContrasena)
                    .addComponent(jPasswordFieldCampoContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModificarContrasena))
                .addGap(0, 138, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
        PantallaInicialAdministrador iniciador = new PantallaInicialAdministrador(Usuario);
        iniciador.setVisible(true);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarUsuarioActionPerformed
        // TODO add your handling code here:
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado= false;
        if(this.Usuario.equals(this.jTextFieldCampoUsuario.getText()))
        {
            JOptionPane.showMessageDialog(null, "El usuario anterior es el mismo al nuevo.");
        }
        else if(!this.jTextFieldCampoUsuario.getText().isEmpty())
        {
            resultado=consulta.ModificarUsuario(Usuario, this.jTextFieldCampoUsuario.getText());
            if(resultado)
            {
                JOptionPane.showMessageDialog(null, "Se modifico el usuario.");
                Usuario=this.jTextFieldCampoUsuario.getText();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo modificar el usuario.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo Usuario vacio.");
        }
    }//GEN-LAST:event_jButtonModificarUsuarioActionPerformed

    private void jButtonModificarContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarContrasenaActionPerformed
        // TODO add your handling code here:
        consultasBaseDeDatos consulta = new BaseDeDatos();
        boolean resultado= false;

        if(!this.jPasswordFieldCampoContrasena.getText().isEmpty())
        {
            resultado=consulta.ModificarContrasena(Usuario, this.jPasswordFieldCampoContrasena.getText());
            if(resultado)
            {
                JOptionPane.showMessageDialog(null, "Se modifico la contraseña.");
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se pudo modificar la contraseña.");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Campo contraseña vacio.");
        }
        
        
    }//GEN-LAST:event_jButtonModificarContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarContrasena;
    private javax.swing.JButton jButtonModificarUsuario;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelEtiquetaContrasena;
    private javax.swing.JLabel jLabelEtiquetaUsuario;
    private javax.swing.JLabel jLabelMensajeInicial;
    private javax.swing.JPasswordField jPasswordFieldCampoContrasena;
    private javax.swing.JTextField jTextFieldCampoUsuario;
    // End of variables declaration//GEN-END:variables
}
