/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author juank
 */
public class PantallaGestionDomiciliarios extends javax.swing.JFrame {
    String usuario = "";
    /**
     * Creates new form PantallaGestionDomiciliarios
     */
    public PantallaGestionDomiciliarios() {
        initComponents();
    }
    public PantallaGestionDomiciliarios(String usuario) {
        initComponents();
        this.usuario=usuario;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonCrearDomiciliario = new javax.swing.JButton();
        jButtonEliminarDomiciliario = new javax.swing.JButton();
        jButtonModificarDomiciliario = new javax.swing.JButton();
        jButtonVerDomiciliarios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });

        jLabel1.setText("Gestion domiciliario");

        jButtonCrearDomiciliario.setText("Crear domiciliario");
        jButtonCrearDomiciliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearDomiciliarioActionPerformed(evt);
            }
        });

        jButtonEliminarDomiciliario.setText("Eliminar domiciliario");
        jButtonEliminarDomiciliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarDomiciliarioActionPerformed(evt);
            }
        });

        jButtonModificarDomiciliario.setText("Modificar domiciliario");
        jButtonModificarDomiciliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarDomiciliarioActionPerformed(evt);
            }
        });

        jButtonVerDomiciliarios.setText("Ver domiciliarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAtras))
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonModificarDomiciliario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminarDomiciliario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCrearDomiciliario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVerDomiciliarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAtras)
                    .addComponent(jLabel1))
                .addGap(69, 69, 69)
                .addComponent(jButtonCrearDomiciliario)
                .addGap(29, 29, 29)
                .addComponent(jButtonEliminarDomiciliario)
                .addGap(28, 28, 28)
                .addComponent(jButtonModificarDomiciliario)
                .addGap(18, 18, 18)
                .addComponent(jButtonVerDomiciliarios)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        PantallaInicialRestaurante pantalla = new PantallaInicialRestaurante(usuario);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonCrearDomiciliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearDomiciliarioActionPerformed
        PantallaCrearDomiciliario pantalla = new PantallaCrearDomiciliario(usuario);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCrearDomiciliarioActionPerformed

    private void jButtonEliminarDomiciliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarDomiciliarioActionPerformed
        PantallaEliminarDomiciliario pantalla = new PantallaEliminarDomiciliario(usuario);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonEliminarDomiciliarioActionPerformed

    private void jButtonModificarDomiciliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarDomiciliarioActionPerformed
        PantallaModificarDomiciliario pantalla = new PantallaModificarDomiciliario(usuario);
        pantalla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonModificarDomiciliarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDomiciliarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDomiciliarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDomiciliarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaGestionDomiciliarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaGestionDomiciliarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCrearDomiciliario;
    private javax.swing.JButton jButtonEliminarDomiciliario;
    private javax.swing.JButton jButtonModificarDomiciliario;
    private javax.swing.JButton jButtonVerDomiciliarios;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
