/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author samyf
 */
public class PantallaInicialRestaurante extends javax.swing.JFrame {
    String usuario=" ";
    /**
     * Creates new form PantallaInicialRestaurante
     */
    public PantallaInicialRestaurante() {
        initComponents();
        Transparencia();
        this.setLocationRelativeTo(null);
        
    }
    public PantallaInicialRestaurante(String usuario) {
        initComponents();
        Transparencia();
        this.setLocationRelativeTo(null);
        this.usuario=usuario;
        nombreRest.setText(usuario);
        consultasBaseDeDatos consulta = new BaseDeDatos();
        ImageIcon imagenPoner = consulta.ImagenRestaurante(usuario);
        Icon imagen = new ImageIcon(imagenPoner.getImage().getScaledInstance(this.jLabelImagenRestaurante.getWidth(), this.jLabelImagenRestaurante.getHeight(), Image.SCALE_SMOOTH));//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        this.jLabelImagenRestaurante.setIcon(imagen);//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    }
    
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreRest = new javax.swing.JLabel();
        jButtonGestionarPlatos = new javax.swing.JButton();
        jButtonCerrarSesion = new javax.swing.JButton();
        jButtonVerPedidosDeClientes = new javax.swing.JButton();
        jLabelImagenRestaurante = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonVerResenaDeUsuario = new javax.swing.JButton();
        jButtonGestionarDomiciliario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreRest.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        nombreRest.setForeground(new java.awt.Color(255, 255, 255));
        nombreRest.setText("jLabel2");
        getContentPane().add(nombreRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 370, -1));

        jButtonGestionarPlatos.setBorder(null);
        jButtonGestionarPlatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarPlatosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGestionarPlatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 180, 170, 150));

        jButtonCerrarSesion.setBorder(null);
        jButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 90, 70));

        jButtonVerPedidosDeClientes.setBorder(null);
        jButtonVerPedidosDeClientes.setBorderPainted(false);
        jButtonVerPedidosDeClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerPedidosDeClientesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerPedidosDeClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 170, 150));
        getContentPane().add(jLabelImagenRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 110));

        jButton1.setText("jButton1");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 300, 50));

        jButtonVerResenaDeUsuario.setBorder(null);
        jButtonVerResenaDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerResenaDeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVerResenaDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 180, 150));

        jButtonGestionarDomiciliario.setBorder(null);
        jButtonGestionarDomiciliario.setBorderPainted(false);
        jButtonGestionarDomiciliario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGestionarDomiciliarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGestionarDomiciliario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 170, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaRestauranteInicio.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
        this.dispose();
        InicioSesion iniciador= new InicioSesion();
        iniciador.setVisible(true);
    }//GEN-LAST:event_jButtonCerrarSesionActionPerformed

    private void jButtonGestionarPlatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarPlatosActionPerformed
        PantallaGestionPlatos pantallaGestionar = new PantallaGestionPlatos(usuario);
        pantallaGestionar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonGestionarPlatosActionPerformed

    private void jButtonGestionarDomiciliarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGestionarDomiciliarioActionPerformed
       PantallaGestionDomiciliarios pantallaGestionarDomiciliarios = new PantallaGestionDomiciliarios(usuario);
       pantallaGestionarDomiciliarios.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonGestionarDomiciliarioActionPerformed

    private void jButtonVerPedidosDeClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerPedidosDeClientesActionPerformed
 PedidosRest p = new PedidosRest(usuario);
       p.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonVerPedidosDeClientesActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        PantallaClientesActivos pantallaActivos = new PantallaClientesActivos(usuario);
        pantallaActivos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonVerResenaDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerResenaDeUsuarioActionPerformed
        // TODO add your handling code here:
        PantallaVerResenhasRestaurante p = new PantallaVerResenhasRestaurante(this.usuario);
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVerResenaDeUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public void Transparencia ()
    {
        jButtonCerrarSesion.setOpaque(false);
        jButtonCerrarSesion.setBackground(new Color(0, 0, 0, 0));
        jButtonGestionarDomiciliario.setOpaque(false);
        jButtonGestionarDomiciliario.setBackground(new Color(0, 0, 0, 0));
        jButtonGestionarPlatos.setOpaque(false);
        jButtonGestionarPlatos.setBackground(new Color(0, 0, 0, 0));
        jButtonVerPedidosDeClientes.setOpaque(false);
        jButtonVerPedidosDeClientes.setBackground(new Color(0, 0, 0, 0));
        jButtonVerResenaDeUsuario.setOpaque(false);        
        jButtonVerResenaDeUsuario.setBackground(new Color(0, 0, 0, 0));      
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaInicialRestaurante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaInicialRestaurante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonCerrarSesion;
    private javax.swing.JButton jButtonGestionarDomiciliario;
    private javax.swing.JButton jButtonGestionarPlatos;
    private javax.swing.JButton jButtonVerPedidosDeClientes;
    private javax.swing.JButton jButtonVerResenaDeUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImagenRestaurante;
    private javax.swing.JLabel nombreRest;
    // End of variables declaration//GEN-END:variables
}
