/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Tony
 */
public class PantallaVerPedidos extends javax.swing.JFrame {

    String cliente;
    String rest;
    String domdoc;
    DefaultListModel listaPedidosActivos = new DefaultListModel();
    DefaultListModel listaPedidosAnteriores = new DefaultListModel();

    /**
     * Creates new form PantallaVerPedidos
     */
    public PantallaVerPedidos() {

        initComponents();
        this.setLocationRelativeTo(null);
        this.transparencia();

    }

    public PantallaVerPedidos(String Usuario) {

        initComponents();
        this.setLocationRelativeTo(null);
        this.transparencia();
        this.cliente = Usuario;
        consultasBaseDeDatos consulta = new BaseDeDatos();
        this.listaPedidosActivos = consulta.BuscarPedidosEnCurso(Usuario);
        this.jListPedidosEnCurso.setModel(listaPedidosActivos);
        this.listaPedidosAnteriores = consulta.BuscarPedidosAnteriores(cliente);
        this.jListPedidosEntregados.setModel(listaPedidosAnteriores);

    }

    public PantallaVerPedidos(String Usuario, String rest) {

        initComponents();
        this.setLocationRelativeTo(null);
        this.transparencia();
        this.cliente = Usuario;
        consultasBaseDeDatos consulta = new BaseDeDatos();
        this.listaPedidosActivos = consulta.BuscarPedidosEnCurso(Usuario);
        this.jListPedidosEnCurso.setModel(listaPedidosActivos);
        this.listaPedidosAnteriores = consulta.BuscarPedidosAnteriores(cliente);
        this.jListPedidosEntregados.setModel(listaPedidosAnteriores);
        res.setText(rest);

    }

    public void transparencia() {
        this.jButtonAtras.setOpaque(false);
        this.jButtonAtras.setBackground(new Color(0, 0, 0, 0));
        this.jButtonCalificar.setOpaque(false);
        this.jButtonCalificar.setBackground(new Color(0, 0, 0, 0));
        this.jButtonEstadoPedido.setOpaque(false);
        this.jButtonEstadoPedido.setBackground(new Color(0, 0, 0, 0));
        this.jButtonVerInconvenientes.setOpaque(false);
        this.jButtonVerInconvenientes.setBackground(new Color(0, 0, 0, 0));
        this.BotonAgregarFavorito.setOpaque(false);
        this.BotonAgregarFavorito.setBackground(new Color(0, 0, 0, 0));
        this.BotonVerPedidosFavoritos.setOpaque(false);
        this.BotonVerPedidosFavoritos.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        res = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListPedidosEnCurso = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPedidosEntregados = new javax.swing.JList();
        jButtonEstadoPedido = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jButtonCalificar = new javax.swing.JButton();
        BotonAgregarFavorito = new javax.swing.JButton();
        BotonVerPedidosFavoritos = new javax.swing.JButton();
        jButtonVerInconvenientes = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 690));
        setMinimumSize(new java.awt.Dimension(800, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jListPedidosEnCurso.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jListPedidosEnCurso);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 280, 170));

        jListPedidosEntregados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListPedidosEntregados);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 280, 160));

        jButtonEstadoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEstadoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonEstadoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 233, 120, 40));

        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 70, 90));

        jButtonCalificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalificarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 590, 100, 30));

        BotonAgregarFavorito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAgregarFavoritoActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAgregarFavorito, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 629, 210, 40));

        BotonVerPedidosFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerPedidosFavoritosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVerPedidosFavoritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 230, 40));
        getContentPane().add(jButtonVerInconvenientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 210, 40));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PantallaVerPedidos.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEstadoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEstadoPedidoActionPerformed

        if (this.jListPedidosEnCurso.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un pedido");
        } else {
            EstadoPedido p = new EstadoPedido(Integer.parseInt(this.jListPedidosEnCurso.getSelectedValue().toString()), cliente, res.getText());
            p.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButtonEstadoPedidoActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed

        PantallaClienteInicio p = new PantallaClienteInicio(cliente);
        p.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButtonAtrasActionPerformed

    private void jButtonCalificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalificarActionPerformed

        if (this.jListPedidosEntregados.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un pedido");
        } else {
            int pedidoid = Integer.parseInt(this.jListPedidosEntregados.getSelectedValue().toString());
            consultasBaseDeDatos consulta = new BaseDeDatos();
            rest = consulta.ObtenerRestauranteDomicilio(pedidoid);
            domdoc = consulta.ObtenerDomiciliarioDomicilio(pedidoid);
            PantallaSatisfacción p = new PantallaSatisfacción(pedidoid, rest, domdoc, cliente);
            p.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_jButtonCalificarActionPerformed

    private void BotonAgregarFavoritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAgregarFavoritoActionPerformed
        // TODO add your handling code here:

        if (this.jListPedidosEnCurso.getSelectedValue() == null) {
            JOptionPane.showMessageDialog(null, "Por favor seleccione un pedido");
        } else {
            consultasBaseDeDatos consulta = new BaseDeDatos();
            if (consulta.agregarPedidoAFavoritos(cliente, this.jListPedidosEnCurso.getSelectedValue().toString())) {
                JOptionPane.showMessageDialog(null, "Se agrego correctamente");
            } else {
                JOptionPane.showMessageDialog(null, "error al agregar a favoritos");
            }

        }

    }//GEN-LAST:event_BotonAgregarFavoritoActionPerformed

    private void BotonVerPedidosFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerPedidosFavoritosActionPerformed
        // TODO add your handling code here:
        PedidosFavoritos p = new PedidosFavoritos(cliente);
        p.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_BotonVerPedidosFavoritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaVerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaVerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaVerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaVerPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaVerPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAgregarFavorito;
    private javax.swing.JButton BotonVerPedidosFavoritos;
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonCalificar;
    private javax.swing.JButton jButtonEstadoPedido;
    private javax.swing.JButton jButtonVerInconvenientes;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JList jListPedidosEnCurso;
    private javax.swing.JList jListPedidosEntregados;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel res;
    // End of variables declaration//GEN-END:variables
}
