/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author gato
 */
public class PantallaModificarCliente extends javax.swing.JFrame {

    /**
     * Creates new form PantallaModificarCliente
     */
    public PantallaModificarCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }
    
    public PantallaModificarCliente(String usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        LabelNombreUsuario.setText(usuario);
        
    }

    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LabelNombreUsuario = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TF_ModificarNombreCliente = new javax.swing.JTextField();
        BotonModificarNombreCliente = new javax.swing.JButton();
        TF_ModificarApellidoCliente = new javax.swing.JTextField();
        BotonModificarApellidoCliente = new javax.swing.JButton();
        TF_ModificarDireccionCliente = new javax.swing.JTextField();
        BotonModificarDireccionCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Modifique su perfil: ");

        LabelNombreUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelNombreUsuario.setText("Nombre de usuario");

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarPantallaInicialCliente(evt);
            }
        });

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido");

        jLabel5.setText("Dirección");

        TF_ModificarNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_ModificarNombreClienteActionPerformed(evt);
            }
        });

        BotonModificarNombreCliente.setText("Cambiar");
        BotonModificarNombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarNombreClienteActionPerformed(evt);
            }
        });

        BotonModificarApellidoCliente.setText("Cambiar");
        BotonModificarApellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarApellidoClienteActionPerformed(evt);
            }
        });

        BotonModificarDireccionCliente.setText("Cambiar");
        BotonModificarDireccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarDireccionClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(LabelNombreUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TF_ModificarNombreCliente)
                            .addComponent(TF_ModificarApellidoCliente)
                            .addComponent(TF_ModificarDireccionCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonModificarNombreCliente)
                            .addComponent(BotonModificarApellidoCliente)
                            .addComponent(BotonModificarDireccionCliente))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LabelNombreUsuario))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TF_ModificarNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModificarNombreCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TF_ModificarApellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModificarApellidoCliente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TF_ModificarDireccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonModificarDireccionCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegresarPantallaInicialCliente(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarPantallaInicialCliente
        // TODO add your handling code here:
        PantallaInicialCliente pantalla = new PantallaInicialCliente();
                    pantalla.setVisible(true);
                    this.dispose();
        
    }//GEN-LAST:event_BotonRegresarPantallaInicialCliente

    private void TF_ModificarNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_ModificarNombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_ModificarNombreClienteActionPerformed

    private void BotonModificarNombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarNombreClienteActionPerformed
        // TODO add your handling code here:
        
        consultasBaseDeDatos consulta = new BaseDeDatos();
        if(consulta.ModificarNombreCliente(LabelNombreUsuario.getText(), TF_ModificarNombreCliente.getText()))
        {
                    JOptionPane.showMessageDialog(null, "Se modifico el nombre del cliente con exito");
        }
        else
        {
            TF_ModificarNombreCliente.setText("");
            JOptionPane.showMessageDialog(null, "Error al Modificar el nombre del cliente");
        }
        
        
        
        
    }//GEN-LAST:event_BotonModificarNombreClienteActionPerformed

    private void BotonModificarApellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarApellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModificarApellidoClienteActionPerformed

    private void BotonModificarDireccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarDireccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonModificarDireccionClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaModificarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonModificarApellidoCliente;
    private javax.swing.JButton BotonModificarDireccionCliente;
    private javax.swing.JButton BotonModificarNombreCliente;
    private javax.swing.JLabel LabelNombreUsuario;
    private javax.swing.JTextField TF_ModificarApellidoCliente;
    private javax.swing.JTextField TF_ModificarDireccionCliente;
    private javax.swing.JTextField TF_ModificarNombreCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
