/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
/**
 *
 * @author Estefania
 */
public class PantallaBusquedaPR extends javax.swing.JFrame {
    
    DefaultListModel restaurantes;
    
    
    public PantallaBusquedaPR() {
        initComponents();
        restaurantes = new DefaultListModel();
        transparenciaDelBoton();
        inicioVentana();
        this.setLocationRelativeTo(null);   
    }
    /*funcion para agregar icono del programa*/
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/lentti.png"));
        return retValue;
    }
    public void inicioVentana(){
        Fondo1.setVisible(true);
        Fondo2.setVisible(false);
        BotonBuscar.setVisible(true);
        InfoBusqueda.setVisible(false);
        ListaBusquedaRestaurantes.setVisible(false);
        BotonRealizarOtra.setVisible(false);
        BotonVerRestaurante.setVisible(false);
        EscribirConsulta.setVisible(true);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EscribirConsulta = new javax.swing.JTextField();
        BotonAtrasBusqueda = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        ListaBusquedaRestaurantes = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        BotonVerRestaurante = new javax.swing.JButton();
        BotonRealizarOtra = new javax.swing.JButton();
        Fondo1 = new javax.swing.JLabel();
        InfoBusqueda = new javax.swing.JTextField();
        Fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EscribirConsulta.setBackground(new java.awt.Color(235, 235, 235));
        EscribirConsulta.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        EscribirConsulta.setBorder(null);
        getContentPane().add(EscribirConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 320, 40));

        BotonAtrasBusqueda.setBackground(new java.awt.Color(255, 255, 255));
        BotonAtrasBusqueda.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        BotonAtrasBusqueda.setText("<<  Atrás");
        BotonAtrasBusqueda.setBorder(null);
        getContentPane().add(BotonAtrasBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        BotonBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(BotonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, 40));

        jList1.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListaBusquedaRestaurantes.setViewportView(jList1);

        getContentPane().add(ListaBusquedaRestaurantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 720, 100));

        BotonVerRestaurante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonVerRestauranteMouseClicked(evt);
            }
        });
        getContentPane().add(BotonVerRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 230, 40));

        BotonRealizarOtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRealizarOtraMouseClicked(evt);
            }
        });
        getContentPane().add(BotonRealizarOtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 390, 50));

        Fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BusquedaPR.png"))); // NOI18N
        getContentPane().add(Fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        InfoBusqueda.setEditable(false);
        InfoBusqueda.setBackground(new java.awt.Color(235, 235, 235));
        InfoBusqueda.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        InfoBusqueda.setText("jTextField1");
        InfoBusqueda.setBorder(null);
        InfoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoBusquedaActionPerformed(evt);
            }
        });
        getContentPane().add(InfoBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 360, 40));

        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BusquedaPR2.png"))); // NOI18N
        getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonBuscarMouseClicked
        // TODO add your handling code here:
        Fondo1.setVisible(false);
        Fondo2.setVisible(true);
        ListaBusquedaRestaurantes.setVisible(true);
        BotonBuscar.setVisible(false);
        InfoBusqueda.setVisible(true);
        BotonRealizarOtra.setVisible(true);
        BotonVerRestaurante.setVisible(true);
        EscribirConsulta.setVisible(false);
        
        
    }//GEN-LAST:event_BotonBuscarMouseClicked

    private void InfoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoBusquedaActionPerformed

    private void BotonRealizarOtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRealizarOtraMouseClicked
        // TODO add your handling code here:
        //Boton realizar otra busqueda
        
        visibilidadPantalla2();
        MostrarRestaurantes();
    }//GEN-LAST:event_BotonRealizarOtraMouseClicked
    
    public void visibilidadPantalla2(){
        Fondo1.setVisible(true);
        Fondo2.setVisible(false);
        BotonBuscar.setVisible(true);
        InfoBusqueda.setVisible(false);
        ListaBusquedaRestaurantes.setVisible(false);
        BotonRealizarOtra.setVisible(false);
        BotonVerRestaurante.setVisible(false);
        
    }
    private void BotonVerRestauranteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonVerRestauranteMouseClicked
        // TODO add your handling code here:
        PantallaMPerfilRest pantallaMPerfilRest = new PantallaMPerfilRest ();
        pantallaMPerfilRest.setVisible(true);
        this.dispose();   
        
        
    }//GEN-LAST:event_BotonVerRestauranteMouseClicked
    
    public void MostrarRestaurantes(){
        
        restaurantes.clear();
        ArrayList<String> rest = new ArrayList<>();
        if( !EscribirConsulta.getText().equals(null) ){
           //rest = BuscarCriterio( EscribirConsulta.getText()); (Tiene que retorar un string)
        }
        for( String i: rest )
            restaurantes.addElement(i);
        jList1.setModel(restaurantes); //Muestra los restaurantes que coinciden en la busqueda
    }
    public void transparenciaDelBoton(){
        BotonBuscar.setOpaque(false);
        BotonBuscar.setBackground(new Color(0,0,0,0));
        BotonRealizarOtra.setOpaque(false);
        BotonRealizarOtra.setBackground(new Color(0,0,0,0));
        BotonVerRestaurante.setOpaque(false);
        BotonVerRestaurante.setBackground(new Color(0,0,0,0));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBusquedaPR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaBusquedaPR().setVisible(true);
            }
        });
        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtrasBusqueda;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonRealizarOtra;
    private javax.swing.JButton BotonVerRestaurante;
    private javax.swing.JTextField EscribirConsulta;
    private javax.swing.JLabel Fondo1;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JTextField InfoBusqueda;
    private javax.swing.JScrollPane ListaBusquedaRestaurantes;
    private javax.swing.JList<String> jList1;
    // End of variables declaration//GEN-END:variables
}
