/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Controlador.consultasBaseDeDatos;
import Modelo.BaseDeDatos;
import java.awt.Color;
import javax.swing.DefaultListModel;

/**
 *
 * @author gato
 */
public class PedidosFavoritos extends javax.swing.JFrame {

    
    String usuarioActual;
    DefaultListModel listapedidosfavoritps = new DefaultListModel();
    /**
     * Creates new form PedidosFavoritos
     */
    public PedidosFavoritos() {
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciaDelBoton();
    }
    
    public PedidosFavoritos(String pUsuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        transparenciaDelBoton();
        usuarioActual = pUsuario;
        mostrarInformacion();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonRegresarAVerPedidos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JListPedidosFavoritos = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotonRegresarAVerPedidos.setBorder(null);
        getContentPane().add(BotonRegresarAVerPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 40, 110, 40));

        JListPedidosFavoritos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(JListPedidosFavoritos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 180, 450, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pantallaPedidosFavoritos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PedidosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PedidosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PedidosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PedidosFavoritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PedidosFavoritos().setVisible(true);
            }
        });
    }
    
    public void transparenciaDelBoton(){
        BotonRegresarAVerPedidos.setOpaque(false);
        BotonRegresarAVerPedidos.setBackground(new Color(0,0,0,0));
        
     
    }
    
    public void mostrarInformacion()
    {
        consultasBaseDeDatos consulta = new BaseDeDatos();
        
        for (String pedido : consulta.darPedidoAFavoritos(usuarioActual)) 
       {
           for (String plato : consulta.darPlatoSegunPedido(pedido)) {
               listapedidosfavoritps.addElement(plato);
           }
           
       }
       
       this.JListPedidosFavoritos.setModel(listapedidosfavoritps);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegresarAVerPedidos;
    private javax.swing.JList<String> JListPedidosFavoritos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
